In [1]:

import pandas as pd
from pathlib import Path

project_path = Path(
    r"C:\Users\ANKIT TRIPATHI\Supply-Chain-Inventory-Analysis"
)

data_path = project_path / "data" / "Supply_Chain_Cleaned.csv"

df_powerbi = pd.read_csv(data_path)

df_powerbi["Order_Date"] = pd.to_datetime(
    df_powerbi["Order_Date"]
)

df_powerbi["Delivery_Date"] = pd.to_datetime(
    df_powerbi["Delivery_Date"]
)

print("Dataset loaded successfully!")
print("Dataset shape:", df_powerbi.shape)
print("\nColumn names:")
print(df_powerbi.columns.tolist())

display(df_powerbi.head())

Dataset loaded successfully!
Dataset shape: (15000, 14)

Column names:
['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit']

,Product_ID,Product_Name,Category,Supplier_Name,Order_Date,Delivery_Date,Stock_Quantity,Reorder_Level,Units_Sold,Purchase_Cost,Selling_Price,Warehouse_Location,Shipping_Time_Days,Profit_Per_Unit
0,PROD1000,Tablet,Fashion,Supplier D,2023-08-02,2023-08-07,3,59,241,1800,2081,Chennai,5,281
1,PROD1001,Tablet,Fashion,Supplier D,2024-04-11,2024-04-13,118,105,70,1950,2169,Hyderabad,2,219
2,PROD1002,Mixer,Sports,Supplier A,2024-08-16,2024-08-20,57,108,107,828,1322,Bangalore,4,494
3,PROD1003,TV,Sports,Supplier B,2024-11-30,2024-12-02,420,129,271,317,598,Chennai,2,281
4,PROD1004,Mixer,Fashion,Supplier C,2024-08-03,2024-08-11,401,77,210,645,1061,Mumbai,8,416

In [2]:

# Classify inventory status

df_powerbi["Inventory_Status"] = "Normal"

df_powerbi.loc[
    df_powerbi["Stock_Quantity"] <= df_powerbi["Reorder_Level"],
    "Inventory_Status"
] = "At or Below Reorder Level"

print("Inventory status column added successfully!")

display(
    df_powerbi[
        [
            "Product_Name",
            "Stock_Quantity",
            "Reorder_Level",
            "Inventory_Status"
        ]
    ].head(10)
)

print("\nInventory status counts:")
display(df_powerbi["Inventory_Status"].value_counts())

Inventory status column added successfully!

  Product_Name  Stock_Quantity  Reorder_Level           Inventory_Status
0       Tablet               3             59  At or Below Reorder Level
1       Tablet             118            105                     Normal
2        Mixer              57            108  At or Below Reorder Level
3           TV             420            129                     Normal
4        Mixer             401             77                     Normal
5       Laptop             188            103                     Normal
6       Laptop             173             58                     Normal
7        Mixer             184            140                     Normal
8       Camera             158            122                     Normal
9           TV             473            147                     Normal

Inventory status counts:

Inventory_Status
Normal                       11985
At or Below Reorder Level     3015
Name: count, dtype: int64

In [4]:

print(df_powerbi.columns.tolist())

['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit', 'Inventory_Status']

In [5]:

# Recreate calculated columns safely

df_powerbi["Total_Gross_Profit"] = (
    df_powerbi["Profit_Per_Unit"] *
    df_powerbi["Units_Sold"]
)

df_powerbi["Inventory_Status"] = "Normal"

df_powerbi.loc[
    df_powerbi["Stock_Quantity"] <= df_powerbi["Reorder_Level"],
    "Inventory_Status"
] = "At or Below Reorder Level"

print("Calculated columns created successfully!")

display(
    df_powerbi[
        [
            "Product_Name",
            "Units_Sold",
            "Profit_Per_Unit",
            "Total_Gross_Profit",
            "Inventory_Status"
        ]
    ].head()
)

Calculated columns created successfully!

,Product_Name,Units_Sold,Profit_Per_Unit,Total_Gross_Profit,Inventory_Status
0,Tablet,241,281,67721,At or Below Reorder Level
1,Tablet,70,219,15330,Normal
2,Mixer,107,494,52858,At or Below Reorder Level
3,TV,271,281,76151,Normal
4,Mixer,210,416,87360,Normal

In [6]:

print("Dataset shape:", df_powerbi.shape)

print("Missing values:", df_powerbi.isnull().sum().sum())
print("Duplicate rows:", df_powerbi.duplicated().sum())

print(
    "Gross profit calculation valid:",
    (
        df_powerbi["Total_Gross_Profit"]
        == df_powerbi["Profit_Per_Unit"] * df_powerbi["Units_Sold"]
    ).all()
)

print("\nInventory status counts:")
display(df_powerbi["Inventory_Status"].value_counts())

Dataset shape: (15000, 16)
Missing values: 0
Duplicate rows: 0
Gross profit calculation valid: True

Inventory status counts:

Inventory_Status
Normal                       11985
At or Below Reorder Level     3015
Name: count, dtype: int64

In [7]:

# Export final dataset for Power BI

output_path = (
    project_path / "data" / "Supply_Chain_PowerBI.csv"
)

df_powerbi.to_csv(output_path, index=False)

print("Power BI dataset exported successfully!")
print("Saved location:", output_path)
print("Rows:", df_powerbi.shape[0])
print("Columns:", df_powerbi.shape[1])
print("File exists:", output_path.exists())

Power BI dataset exported successfully!
Saved location: C:\Users\ANKIT TRIPATHI\Supply-Chain-Inventory-Analysis\data\Supply_Chain_PowerBI.csv
Rows: 15000
Columns: 16
File exists: True

In [8]:

# Verify the exported CSV

df_check = pd.read_csv(output_path)

print("Export verification")
print("-------------------")
print("Shape:", df_check.shape)
print("Missing values:", df_check.isnull().sum().sum())
print("Duplicate rows:", df_check.duplicated().sum())
print("\nColumns:")
print(df_check.columns.tolist())

display(df_check.head())

Export verification
-------------------
Shape: (15000, 16)
Missing values: 0
Duplicate rows: 0

Columns:
['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit', 'Inventory_Status', 'Total_Gross_Profit']

,Product_ID,Product_Name,Category,Supplier_Name,Order_Date,Delivery_Date,Stock_Quantity,Reorder_Level,Units_Sold,Purchase_Cost,Selling_Price,Warehouse_Location,Shipping_Time_Days,Profit_Per_Unit,Inventory_Status,Total_Gross_Profit
0,PROD1000,Tablet,Fashion,Supplier D,2023-08-02,2023-08-07,3,59,241,1800,2081,Chennai,5,281,At or Below Reorder Level,67721
1,PROD1001,Tablet,Fashion,Supplier D,2024-04-11,2024-04-13,118,105,70,1950,2169,Hyderabad,2,219,Normal,15330
2,PROD1002,Mixer,Sports,Supplier A,2024-08-16,2024-08-20,57,108,107,828,1322,Bangalore,4,494,At or Below Reorder Level,52858
3,PROD1003,TV,Sports,Supplier B,2024-11-30,2024-12-02,420,129,271,317,598,Chennai,2,281,Normal,76151
4,PROD1004,Mixer,Fashion,Supplier C,2024-08-03,2024-08-11,401,77,210,645,1061,Mumbai,8,416,Normal,87360

In [9]:

print("DataFrame columns:")
print(df_powerbi.columns.tolist())

print("\nTotal_Gross_Profit exists:")
print("Total_Gross_Profit" in df_powerbi.columns)

print("\nExported CSV columns:")
df_check = pd.read_csv(output_path)
print(df_check.columns.tolist())

print("\nExported CSV shape:", df_check.shape)

DataFrame columns:
['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit', 'Inventory_Status', 'Total_Gross_Profit']

Total_Gross_Profit exists:
True

Exported CSV columns:
['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit', 'Inventory_Status', 'Total_Gross_Profit']

Exported CSV shape: (15000, 16)

In [10]:

df_powerbi["Total_Gross_Profit"] = (
    df_powerbi["Profit_Per_Unit"] *
    df_powerbi["Units_Sold"]
)

df_powerbi["Inventory_Status"] = "Normal"

df_powerbi.loc[
    df_powerbi["Stock_Quantity"] <= df_powerbi["Reorder_Level"],
    "Inventory_Status"
] = "At or Below Reorder Level"

df_powerbi.to_csv(output_path, index=False)

print("CSV updated:", output_path)
print("Columns:", len(pd.read_csv(output_path, nrows=1).columns))
print(pd.read_csv(output_path, nrows=1).columns.tolist())

CSV updated: C:\Users\ANKIT TRIPATHI\Supply-Chain-Inventory-Analysis\data\Supply_Chain_PowerBI.csv
Columns: 16
['Product_ID', 'Product_Name', 'Category', 'Supplier_Name', 'Order_Date', 'Delivery_Date', 'Stock_Quantity', 'Reorder_Level', 'Units_Sold', 'Purchase_Cost', 'Selling_Price', 'Warehouse_Location', 'Shipping_Time_Days', 'Profit_Per_Unit', 'Inventory_Status', 'Total_Gross_Profit']